//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;

namespace AppDepartmentEmployee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Employees
    {
        public int id { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Direccion Obligatoria")]
        [DisplayName("Dirección")]
        public string direccion { get; set; }
        [DisplayName("Telefono")]
        public string telefono { get; set; }
        [Required(ErrorMessage ="Edad Obligatoria")]
        [DisplayName("Edad")]
        public int edad { get; set; }
        [DisplayName("Departamento")]
        public Nullable<int> department_id { get; set; }
        [DisplayName("RFC")]
        public string RFC { get; set; }
        public virtual Departments Departments { get; set; }
    }
}
